FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY GentleBook.Api.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish GentleBook.Api.csproj -c Release -r linux-x64 --self-contained false -p:UseAppHost=false -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 5000
ENTRYPOINT ["dotnet", "GentleBook.Api.dll"]
